import { ensureP1Snapshot, nextEntityId, appendAudit } from './p1.mjs';

const DAY=86_400_000;
function round(value){return Math.round((Number(value)+Number.EPSILON)*100)/100;}
function uniqueId(prefix){const id=globalThis.crypto?.randomUUID?.()??`${Date.now().toString(36)}-${Math.random().toString(36).slice(2)}`;return `${prefix}-${id}`;}
function iso(value){const d=new Date(value);if(!Number.isFinite(d.getTime()))throw new Error('Data inválida.');return d.toISOString();}
function dateOnly(value){return iso(value).slice(0,10);}
function daysInMonth(year,monthIndex){return new Date(Date.UTC(year,monthIndex+1,0)).getUTCDate();}
function monthlyDate(first,index){const start=new Date(`${dateOnly(first)}T12:00:00Z`);const originalDay=start.getUTCDate();const month=start.getUTCMonth()+index;const year=start.getUTCFullYear()+Math.floor(month/12);const normalizedMonth=((month%12)+12)%12;const day=Math.min(originalDay,daysInMonth(year,normalizedMonth));return `${year}-${String(normalizedMonth+1).padStart(2,'0')}-${String(day).padStart(2,'0')}`;}
function dueFor(first,frequency,index,customDays){if(frequency==='monthly')return monthlyDate(first,index);const days=frequency==='daily'?1:frequency==='weekly'?7:frequency==='biweekly'?14:Math.max(1,Number(customDays)||1);const d=new Date(`${dateOnly(first)}T12:00:00Z`);d.setUTCDate(d.getUTCDate()+days*index);return d.toISOString().slice(0,10);}
function findRental(snapshot,id){const value=snapshot.rentals.find(x=>x.id===id);if(!value)throw new Error('Locação não encontrada.');return value;}
function templateValue(source,path){return path.split('.').reduce((acc,key)=>acc?.[key],source);}
function formatMoney(value){return Number(value||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});}
function contractVariables(snapshot,rentalId){const rental=findRental(snapshot,rentalId),customer=snapshot.customers.find(x=>x.id===rental.customerId)??{},vehicle=snapshot.vehicles.find(x=>x.id===rental.vehicleId)??{},attendant=snapshot.users?.find(x=>x.id===rental.attendantId)??{};return{locadora:{nome:snapshot.settings?.companyName??'',documento:snapshot.settings?.document??'',telefone:snapshot.settings?.phone??'',endereco:snapshot.settings?.address??''},cliente:{nome:customer.name??'',cpf:customer.document??'',documento:customer.document??'',telefone:customer.phone??'',email:customer.email??'',endereco:customer.address??'',cnh:customer.driverLicense?.number??'',categoria_cnh:customer.driverLicense?.category??''},veiculo:{modelo:vehicle.model??'',placa:vehicle.plate??'',ano:vehicle.year??'',cor:vehicle.color??'',categoria:vehicle.category??'',km:vehicle.mileage??'',renavam:vehicle.documents?.renavam??'',chassi:vehicle.documents?.chassis??''},locacao:{id:rental.id,retirada:rental.pickupAt??'',devolucao:rental.returnAt??'',valor_diaria:formatMoney(rental.dailyRate),valor_total:formatMoney(rental.total),dias:rental.days??'',status:rental.status??'',observacoes:rental.notes??''},atendente:{nome:attendant.name??'',usuario:attendant.username??''}};}

export function ensureCommercialSnapshot(input){const snapshot=ensureP1Snapshot(input);snapshot.version=Math.max(Number(snapshot.version||0),4);for(const key of ['contractTemplates','issuedContracts','billingPlans','billingInstallments','collectionActions'])snapshot[key]=Array.isArray(snapshot[key])?snapshot[key]:[];return snapshot;}

export function createContractTemplate(input,draft={},actorId){const snapshot=ensureCommercialSnapshot(input);const name=String(draft.name??'').trim(),body=String(draft.body??'').trim();if(!name||!body)throw new Error('Nome e conteúdo do contrato são obrigatórios.');const now=new Date().toISOString();if(draft.isDefault)snapshot.contractTemplates.forEach(x=>x.isDefault=false);const item={id:uniqueId('CTR'),name,body,active:draft.active!==false,isDefault:Boolean(draft.isDefault),version:1,createdAt:now,updatedAt:now};snapshot.contractTemplates.unshift(item);appendAudit(snapshot,{actorId,action:'contract_template.created',entityType:'contract_template',entityId:item.id,details:{name}});return snapshot;}
export function updateContractTemplate(input,id,patch={},actorId){const snapshot=ensureCommercialSnapshot(input),item=snapshot.contractTemplates.find(x=>x.id===id);if(!item)throw new Error('Modelo de contrato não encontrado.');if(patch.isDefault)snapshot.contractTemplates.forEach(x=>x.isDefault=x.id===id);if(patch.name!=null)item.name=String(patch.name).trim();if(patch.body!=null)item.body=String(patch.body);if(patch.active!=null)item.active=Boolean(patch.active);if(patch.isDefault!=null)item.isDefault=Boolean(patch.isDefault);item.version=Math.max(1,Number(item.version)||1)+1;item.updatedAt=new Date().toISOString();appendAudit(snapshot,{actorId,action:'contract_template.updated',entityType:'contract_template',entityId:id,details:{version:item.version}});return snapshot;}
export function duplicateContractTemplate(input,id,actorId){const snapshot=ensureCommercialSnapshot(input),item=snapshot.contractTemplates.find(x=>x.id===id);if(!item)throw new Error('Modelo de contrato não encontrado.');return createContractTemplate(snapshot,{name:`${item.name} - cópia`,body:item.body},actorId);}
export function deactivateContractTemplate(input,id,actorId){return updateContractTemplate(input,id,{active:false,isDefault:false},actorId);}
export function contractTemplatePreview(input,templateId,rentalId){const snapshot=ensureCommercialSnapshot(input),template=snapshot.contractTemplates.find(x=>x.id===templateId&&x.active!==false);if(!template)throw new Error('Modelo de contrato não encontrado ou inativo.');const vars=contractVariables(snapshot,rentalId),unknownVariables=[];const renderedText=template.body.replace(/{{\s*([\w.]+)\s*}}/g,(full,path)=>{const value=templateValue(vars,path);if(value==null){if(!unknownVariables.includes(path))unknownVariables.push(path);return`[${path}]`;}return String(value);});return{renderedText,unknownVariables};}
export function renderContractTemplate(input,templateId,rentalId){return contractTemplatePreview(input,templateId,rentalId).renderedText;}
export function issueContract(input,{templateId,rentalId}={},actorId){const snapshot=ensureCommercialSnapshot(input),template=snapshot.contractTemplates.find(x=>x.id===templateId);if(!template)throw new Error('Modelo de contrato não encontrado.');const preview=contractTemplatePreview(snapshot,templateId,rentalId);if(preview.unknownVariables.length)throw new Error(`Contrato possui variáveis desconhecidas: ${preview.unknownVariables.join(', ')}.`);const now=new Date().toISOString();const item={id:uniqueId('EMI'),rentalId,templateId,templateName:template.name,templateVersion:template.version,renderedText:preview.renderedText,createdAt:now,updatedAt:now};snapshot.issuedContracts.unshift(item);appendAudit(snapshot,{actorId,action:'contract.issued',entityType:'issued_contract',entityId:item.id,details:{rentalId,templateId,templateVersion:template.version}});return snapshot;}

export function createBillingPlan(input,draft={},actorId){const snapshot=ensureCommercialSnapshot(input),rental=findRental(snapshot,draft.rentalId);const amount=round(draft.amount),occurrences=Math.max(1,Math.floor(Number(draft.occurrences)||1));if(!(amount>0))throw new Error('Valor da cobrança deve ser maior que zero.');const allowed=['daily','weekly','biweekly','monthly','custom'];const frequency=allowed.includes(draft.frequency)?draft.frequency:'monthly';const firstDueAt=dateOnly(draft.firstDueAt);const purpose=draft.purpose==='rental_schedule'?'rental_schedule':'additional';if(snapshot.billingPlans.some(p=>p.active&&p.rentalId===rental.id&&p.frequency===frequency&&p.firstDueAt===firstDueAt&&Number(p.amount)===amount))throw new Error('Já existe uma recorrência ativa equivalente para esta locação.');const now=new Date().toISOString();const plan={id:uniqueId('PLN'),rentalId:rental.id,customerId:rental.customerId,vehicleId:rental.vehicleId,purpose,frequency,customDays:frequency==='custom'?Math.max(1,Number(draft.customDays)||1):null,amount,occurrences,firstDueAt,finePercent:Math.max(0,Number(draft.finePercent)||0),interestMonthlyPercent:Math.max(0,Number(draft.interestMonthlyPercent)||0),active:true,createdAt:now,updatedAt:now};snapshot.billingPlans.unshift(plan);for(let i=0;i<occurrences;i++){const dueAt=dueFor(firstDueAt,frequency,i,plan.customDays),installment={id:uniqueId('PAR'),planId:plan.id,rentalId:rental.id,customerId:rental.customerId,vehicleId:rental.vehicleId,sequence:i+1,dueAt,amount,paidAmount:0,status:'open',payments:[],finePercent:plan.finePercent,interestMonthlyPercent:plan.interestMonthlyPercent,createdAt:now,updatedAt:now};snapshot.billingInstallments.push(installment);snapshot.ledger.unshift({id:nextEntityId('FIN',snapshot.ledger),kind:'billing_receivable',billingPurpose:purpose,installmentId:installment.id,rentalId:rental.id,vehicleId:rental.vehicleId,description:`Cobrança recorrente ${plan.id} parcela ${i+1}`,amount,paidAmount:0,status:'open',dueAt,createdAt:now});}snapshot.billingInstallments.sort((a,b)=>String(a.dueAt).localeCompare(String(b.dueAt)));appendAudit(snapshot,{actorId,action:'billing_plan.created',entityType:'billing_plan',entityId:plan.id,details:{rentalId:rental.id,occurrences,amount,frequency,purpose}});return snapshot;}

export function installmentBalance(installment,asOf=new Date().toISOString()){const principal=Math.max(0,round(Number(installment.amount||0))),paid=round(Number(installment.paidAmount||0));const due=new Date(`${String(installment.dueAt).slice(0,10)}T23:59:59Z`).getTime(),now=new Date(asOf).getTime();const daysLate=Math.max(0,Math.floor((now-due)/DAY));const outstanding=Math.max(0,round(principal-paid));const fine=daysLate>0&&outstanding>0?round(outstanding*(Number(installment.finePercent||0)/100)):0;const interest=daysLate>0&&outstanding>0?round(outstanding*(Number(installment.interestMonthlyPercent||0)/100)*(daysLate/30)):0;const totalDue=round(outstanding+fine+interest);return{principal,paid,outstanding,daysLate,fine,interest,totalDue,balance:totalDue};}
export function recordInstallmentPayment(input,installmentId,{amount,method='PIX',paidAt=new Date().toISOString()}={},actorId){const snapshot=ensureCommercialSnapshot(input),item=snapshot.billingInstallments.find(x=>x.id===installmentId);if(!item)throw new Error('Parcela não encontrada.');const value=round(amount);if(!(value>0))throw new Error('Valor do pagamento deve ser maior que zero.');const due=installmentBalance(item,paidAt);if(value>due.totalDue+0.001)throw new Error('Pagamento excede o saldo da parcela.');const payment={id:uniqueId('PAG'),amount:value,method:String(method),paidAt:iso(paidAt)};item.payments.push(payment);item.paidAmount=round(Number(item.paidAmount||0)+value);const after=installmentBalance(item,paidAt);item.status=after.totalDue<=0.001?'paid':'partial';item.updatedAt=payment.paidAt;const ledger=snapshot.ledger.find(x=>x.installmentId===installmentId);if(ledger){ledger.paidAmount=item.paidAmount;ledger.status=item.status==='paid'?'paid':'partial';ledger.paidAt=item.status==='paid'?payment.paidAt:ledger.paidAt;}const plan=snapshot.billingPlans.find(x=>x.id===item.planId);if(plan?.purpose==='rental_schedule'){const rental=findRental(snapshot,item.rentalId),schedule=snapshot.billingInstallments.filter(x=>x.planId===plan.id&&x.status!=='cancelled');const principalPaid=round(schedule.reduce((sum,x)=>sum+Math.min(Number(x.amount||0),Number(x.paidAmount||0)),0)),paid=Math.min(round(Number(rental.total||0)),principalPaid),parent=snapshot.ledger.find(x=>x.kind==='receivable'&&x.rentalId===rental.id);rental.paymentStatus=paid>=Number(rental.total||0)-0.001?'pago':'aberto';rental.updatedAt=payment.paidAt;if(parent){parent.paidAmount=paid;parent.status=paid>=Number(parent.amount||0)-0.001?'paid':paid>0?'partial':'open';if(parent.status==='paid')parent.paidAt=payment.paidAt;else delete parent.paidAt;}}appendAudit(snapshot,{actorId,action:'billing_installment.paid',entityType:'billing_installment',entityId:item.id,details:{amount:value,method,rentalSchedule:plan?.purpose==='rental_schedule'}});return snapshot;}

export function delinquentInstallments(input,asOf=new Date().toISOString()){const snapshot=ensureCommercialSnapshot(input);return snapshot.billingInstallments.map(item=>({item,balance:installmentBalance(item,asOf)})).filter(row=>!['paid','cancelled'].includes(row.item.status)&&row.balance.daysLate>0&&row.balance.totalDue>0).sort((a,b)=>b.balance.daysLate-a.balance.daysLate);}
function agingKey(days){if(days<=7)return'1-7';if(days<=15)return'8-15';if(days<=30)return'16-30';if(days<=60)return'31-60';return'60+';}
export function delinquencySummary(input,asOf=new Date().toISOString()){const snapshot=ensureCommercialSnapshot(input),rows=delinquentInstallments(snapshot,asOf),aging={'1-7':0,'8-15':0,'16-30':0,'31-60':0,'60+':0};let total=0,dueToday=0,dueNext7Days=0;const customers=new Set(),today=dateOnly(asOf),todayMs=new Date(`${today}T12:00:00Z`).getTime(),limit=todayMs+7*DAY;for(const row of rows){aging[agingKey(row.balance.daysLate)]=round(aging[agingKey(row.balance.daysLate)]+row.balance.totalDue);total=round(total+row.balance.totalDue);customers.add(row.item.customerId);}for(const item of snapshot.billingInstallments.filter(x=>!['paid','cancelled'].includes(x.status))){const balance=installmentBalance(item,asOf);if(balance.totalDue<=0)continue;const due=dateOnly(item.dueAt),dueMs=new Date(`${due}T12:00:00Z`).getTime();if(due===today)dueToday=round(dueToday+balance.totalDue);else if(dueMs>todayMs&&dueMs<=limit)dueNext7Days=round(dueNext7Days+balance.totalDue);}return{total,count:rows.length,customers:customers.size,averageDaysLate:rows.length?Math.round(rows.reduce((s,r)=>s+r.balance.daysLate,0)/rows.length):0,dueToday,dueNext7Days,aging,rows};}
export function recordCollectionAction(input,draft={},actorId){const snapshot=ensureCommercialSnapshot(input),installment=snapshot.billingInstallments.find(x=>x.id===draft.installmentId);if(!installment)throw new Error('Parcela não encontrada.');const now=new Date().toISOString(),note=String(draft.note||'').trim();if(!note)throw new Error('Observação da cobrança é obrigatória.');const item={id:uniqueId('COB'),installmentId:installment.id,rentalId:installment.rentalId,customerId:installment.customerId,channel:String(draft.channel||'Outro'),note,promiseAt:draft.promiseAt||null,nextActionAt:draft.nextActionAt||null,actorId,createdAt:now,updatedAt:now};snapshot.collectionActions.unshift(item);appendAudit(snapshot,{actorId,action:'collection_action.created',entityType:'collection_action',entityId:item.id,details:{installmentId:item.installmentId,channel:item.channel}});return snapshot;}

export function cancelBillingPlan(input,planId,actorId){const snapshot=ensureCommercialSnapshot(input),plan=snapshot.billingPlans.find(x=>x.id===planId);if(!plan)throw new Error('Plano de cobrança não encontrado.');plan.active=false;plan.updatedAt=new Date().toISOString();for(const item of snapshot.billingInstallments.filter(x=>x.planId===planId&&x.status==='open')){item.status='cancelled';item.updatedAt=plan.updatedAt;const ledger=snapshot.ledger.find(x=>x.installmentId===item.id);if(ledger)ledger.status='cancelled';}appendAudit(snapshot,{actorId,action:'billing_plan.cancelled',entityType:'billing_plan',entityId:planId});return snapshot;}
export function billingAlerts(input,asOf=new Date().toISOString(),daysAhead=7){const snapshot=ensureCommercialSnapshot(input),now=new Date(asOf).getTime(),limit=now+Math.max(0,Number(daysAhead)||0)*DAY;return snapshot.billingInstallments.filter(i=>!['paid','cancelled'].includes(i.status)).map(i=>{const due=new Date(`${String(i.dueAt).slice(0,10)}T23:59:59Z`).getTime(),balance=installmentBalance(i,asOf);return{installmentId:i.id,customerId:i.customerId,rentalId:i.rentalId,dueAt:i.dueAt,daysLate:balance.daysLate,totalDue:balance.totalDue,status:balance.daysLate>0?'overdue':due<=limit?'upcoming':'future'};}).filter(x=>x.status!=='future');}
export function filteredDelinquency(input,filters={},asOf=new Date().toISOString()){return delinquentInstallments(input,asOf).filter(({item,balance})=>(!filters.customerId||item.customerId===filters.customerId)&&(!filters.vehicleId||item.vehicleId===filters.vehicleId)&&(!filters.minDays||balance.daysLate>=Number(filters.minDays))&&(!filters.maxDays||balance.daysLate<=Number(filters.maxDays))&&(!filters.startDueAt||String(item.dueAt).slice(0,10)>=String(filters.startDueAt).slice(0,10))&&(!filters.endDueAt||String(item.dueAt).slice(0,10)<=String(filters.endDueAt).slice(0,10)));}
export function vehicleDelinquencyReport(input,asOf=new Date().toISOString()){const snapshot=ensureCommercialSnapshot(input),rows=delinquentInstallments(snapshot,asOf),map=new Map();for(const row of rows){const key=row.item.vehicleId??'',current=map.get(key)??{vehicleId:key,vehicle:snapshot.vehicles.find(x=>x.id===key)?.model??key,count:0,total:0,maxDaysLate:0};current.count++;current.total=round(current.total+row.balance.totalDue);current.maxDaysLate=Math.max(current.maxDaysLate,row.balance.daysLate);map.set(key,current);}return[...map.values()].sort((a,b)=>b.total-a.total);}
export function customerDelinquencyReport(input,asOf=new Date().toISOString()){const snapshot=ensureCommercialSnapshot(input),rows=delinquentInstallments(snapshot,asOf),map=new Map();for(const row of rows){const key=row.item.customerId,current=map.get(key)??{customerId:key,customer:snapshot.customers.find(x=>x.id===key)?.name??key,count:0,total:0,maxDaysLate:0};current.count++;current.total=round(current.total+row.balance.totalDue);current.maxDaysLate=Math.max(current.maxDaysLate,row.balance.daysLate);map.set(key,current);}return[...map.values()].sort((a,b)=>b.total-a.total);}
