import test from 'node:test';
import assert from 'node:assert/strict';
import {createBillingPlan,installmentTotals,registerBillingPayment} from '../src/domain/billing.mjs';

function base({total=1000,paid=0}={}){const payments=paid?[{id:'PAG-1',amount:paid,method:'PIX',paidAt:'2026-09-01T10:00:00Z'}]:[];return {version:4,updatedAt:'2026-09-01T10:00:00Z',customers:[{id:'CLI-1',name:'Ana',active:true,driverLicense:{}}],vehicles:[{id:'VEI-1',model:'Onix',plate:'ABC1D23',availability:'disponivel',documents:{}}],rentals:[{id:'LOC-1',customerId:'CLI-1',vehicleId:'VEI-1',attendantId:'USR-1',pickupAt:'2026-09-01T10:00:00Z',returnAt:'2026-09-10T10:00:00Z',total,payments,paymentStatus:paid>=total?'pago':'aberto',createdAt:'2026-09-01T10:00:00Z',updatedAt:'2026-09-01T10:00:00Z'}],users:[],expenses:[],ledger:[{id:'FIN-1',kind:'receivable',rentalId:'LOC-1',vehicleId:'VEI-1',description:'Locação LOC-1',amount:total,paidAmount:paid,status:paid>=total?'paid':paid?'partial':'open',dueAt:'2026-09-01',createdAt:'2026-09-01T10:00:00Z'}],audit:[],inspections:[],maintenance:[],alertState:{},contractTemplates:[],issuedContracts:[],billingPlans:[],billingInstallments:[],billingPayments:[],collectionActivities:[],settings:{}};}
const sum=x=>Math.round(x.reduce((a,b)=>a+b,0)*100)/100;

test('plano mensal preserva dia-base em meses 28/30/31 e rateia centavos',()=>{const s=createBillingPlan(base(),{rentalId:'LOC-1',cadence:'monthly',installmentCount:3,startDate:'2027-01-31',finePercent:2,interestPercentMonthly:1},'USR-1');assert.deepEqual(s.billingInstallments.map(i=>i.dueAt),['2027-01-31','2027-02-28','2027-03-31']);assert.equal(sum(s.billingInstallments.map(i=>i.principal)),1000);assert.deepEqual(s.billingInstallments.map(i=>i.principal),[333.34,333.33,333.33]);});
test('quinzenal e intervalo personalizado geram datas determinísticas',()=>{let s=createBillingPlan(base(),{rentalId:'LOC-1',cadence:'biweekly',installmentCount:3,startDate:'2026-09-01'},'USR-1');assert.deepEqual(s.billingInstallments.map(i=>i.dueAt),['2026-09-01','2026-09-15','2026-09-29']);s=createBillingPlan(base(),{rentalId:'LOC-1',cadence:'custom',intervalDays:10,installmentCount:3,startDate:'2026-09-01'},'USR-1');assert.deepEqual(s.billingInstallments.map(i=>i.dueAt),['2026-09-01','2026-09-11','2026-09-21']);});
test('parcelamento substitui recebível único sem duplicar receita prevista',()=>{const s=createBillingPlan(base({total:1000,paid:200}),{rentalId:'LOC-1',cadence:'monthly',installmentCount:2,startDate:'2026-10-01'},'USR-1');const receivables=s.ledger.filter(e=>e.kind==='receivable'&&!e.billingFeePaymentId);assert.equal(sum(receivables.map(e=>e.amount)),1000);assert.equal(receivables.find(e=>!e.billingInstallmentId).amount,200);assert.equal(sum(s.billingInstallments.map(i=>i.principal)),800);});
test('multa e juros são pró-rata e congelam ao quitar principal',()=>{let s=createBillingPlan(base({total:100}),{rentalId:'LOC-1',cadence:'monthly',installmentCount:1,startDate:'2026-09-01',finePercent:2,interestPercentMonthly:3},'USR-1');let inst=s.billingInstallments[0];const before=installmentTotals(inst,'2026-09-11T00:00:00Z');assert.equal(before.daysLate,10);assert.equal(before.chargesAccrued,3);s=registerBillingPayment(s,inst.id,{amount:100,method:'PIX',paidAt:'2026-09-11T00:00:00Z'},'USR-1');inst=s.billingInstallments[0];assert.equal(inst.paidPrincipal,100);const frozen=installmentTotals(inst,'2026-09-21T00:00:00Z');assert.equal(frozen.chargesAccrued,3);assert.equal(frozen.chargesOutstanding,3);s=registerBillingPayment(s,inst.id,{amount:3,method:'PIX',paidAt:'2026-09-21T00:00:00Z'},'USR-1');assert.equal(s.billingInstallments[0].status,'paid');assert.equal(s.billingPayments.length,2);assert.equal(s.ledger.filter(e=>e.billingFeePaymentId).reduce((a,e)=>a+e.amount,0),3);});
test('pagamento parcial atualiza parcela, ledger e principal recebido da locação',()=>{let s=createBillingPlan(base({total:300}),{rentalId:'LOC-1',cadence:'monthly',installmentCount:2,startDate:'2026-10-01'},'USR-1');const inst=s.billingInstallments[0];s=registerBillingPayment(s,inst.id,{amount:50,method:'Dinheiro',paidAt:'2026-09-20T00:00:00Z'},'USR-1');const updated=s.billingInstallments.find(i=>i.id===inst.id),entry=s.ledger.find(e=>e.billingInstallmentId===inst.id);assert.equal(updated.paidPrincipal,50);assert.equal(updated.status,'partial');assert.equal(entry.paidAmount,50);assert.equal(s.rentals[0].payments.at(-1).amount,50);});