import test from 'node:test';
import assert from 'node:assert/strict';
import {ensureCommercialSnapshot,createContractTemplate,updateContractTemplate,duplicateContractTemplate,setDefaultContractTemplate,renderContractTemplate,issueContract} from '../src/domain/commercial.mjs';

function base(){return {version:3,updatedAt:'2026-09-14T10:00:00Z',customers:[{id:'CLI-1',name:'Ana',document:'123',phone:'999',email:'a@b.com',address:'Rua A',active:true,driverLicense:{number:'CNH1',category:'B',expiry:'2027-01-01'}}],vehicles:[{id:'VEI-1',model:'Onix',plate:'ABC1D23',year:'2025',mileage:1000,category:'Hatch',color:'Prata',dailyRate:100,availability:'disponivel',documents:{}}],rentals:[{id:'LOC-1',customerId:'CLI-1',vehicleId:'VEI-1',attendantId:'USR-1',pickupAt:'2026-09-15T10:00:00Z',returnAt:'2026-09-17T10:00:00Z',dailyRate:100,days:2,total:200,status:'reserva',paymentStatus:'aberto',notes:'Sem fumaça',payments:[],createdAt:'2026-09-14T10:00:00Z',updatedAt:'2026-09-14T10:00:00Z'}],users:[{id:'USR-1',name:'Victor'}],ledger:[],audit:[],settings:{companyName:'Locadora X',document:'00.000.000/0001-00',phone:'16 9999',address:'Rua X'}};}

test('snapshot v3 migra para v4 com coleções comerciais',()=>{const s=ensureCommercialSnapshot(base());assert.equal(s.version,4);for(const key of ['contractTemplates','issuedContracts','billingPlans','billingInstallments','billingPayments','collectionActivities'])assert.deepEqual(s[key],[]);});

test('template cria, versiona, duplica e define padrão único',()=>{let s=createContractTemplate(base(),{name:'Padrão',body:'Cliente {{cliente.nome}}'},'USR-1');const first=s.contractTemplates[0];assert.equal(first.version,1);assert.equal(first.isDefault,true);s=updateContractTemplate(s,first.id,{body:'Cliente {{cliente.nome}} - {{veiculo.placa}}'},'USR-1');assert.equal(s.contractTemplates[0].version,2);s=duplicateContractTemplate(s,first.id,{name:'Longo'},'USR-1');const second=s.contractTemplates.find(t=>t.name==='Longo');s=setDefaultContractTemplate(s,second.id,'USR-1');assert.equal(s.contractTemplates.find(t=>t.id===second.id).isDefault,true);assert.equal(s.contractTemplates.find(t=>t.id===first.id).isDefault,false);});

test('renderização preenche variáveis e denuncia variável desconhecida',()=>{let s=createContractTemplate(base(),{name:'Padrão',body:'{{locadora.nome}} | {{cliente.nome}} | {{veiculo.placa}} | {{nao.existe}}'},'USR-1');const t=s.contractTemplates[0];const result=renderContractTemplate(s,'LOC-1',t.id);assert.match(result.text,/Locadora X \| Ana \| ABC1D23/);assert.deepEqual(result.unknownVariables,['nao.existe']);});

test('emissão é imutável mesmo se template for editado depois',()=>{let s=createContractTemplate(base(),{name:'Padrão',body:'Contrato A {{cliente.nome}}'},'USR-1');const t=s.contractTemplates[0];s=issueContract(s,{rentalId:'LOC-1',templateId:t.id},'USR-1');const issued=s.issuedContracts[0];assert.equal(issued.renderedBody,'Contrato A Ana');s=updateContractTemplate(s,t.id,{body:'Contrato B {{cliente.nome}}'},'USR-1');assert.equal(s.issuedContracts[0].renderedBody,'Contrato A Ana');assert.equal(s.issuedContracts[0].templateVersion,1);});