import test from 'node:test';
import assert from 'node:assert/strict';
import {createBillingPlan} from '../src/domain/billing.mjs';
import {buildDelinquency,buildAgingReport,addCollectionActivity} from '../src/domain/delinquency.mjs';

function base(){return {version:4,updatedAt:'2026-09-01T10:00:00Z',customers:[{id:'CLI-1',name:'Ana',document:'123',active:true,driverLicense:{}}],vehicles:[{id:'VEI-1',model:'Onix',plate:'ABC1D23',availability:'disponivel',documents:{}}],rentals:[{id:'LOC-1',customerId:'CLI-1',vehicleId:'VEI-1',attendantId:'USR-1',pickupAt:'2026-09-01T10:00:00Z',returnAt:'2026-09-10T10:00:00Z',total:300,payments:[],paymentStatus:'aberto',createdAt:'2026-09-01T10:00:00Z',updatedAt:'2026-09-01T10:00:00Z'}],users:[],expenses:[],ledger:[{id:'FIN-1',kind:'receivable',rentalId:'LOC-1',vehicleId:'VEI-1',description:'Locação LOC-1',amount:300,paidAmount:0,status:'open',dueAt:'2026-09-01',createdAt:'2026-09-01T10:00:00Z'}],audit:[],inspections:[],maintenance:[],alertState:{},contractTemplates:[],issuedContracts:[],billingPlans:[],billingInstallments:[],billingPayments:[],collectionActivities:[],settings:{}};}
function planned(){return createBillingPlan(base(),{rentalId:'LOC-1',cadence:'weekly',installmentCount:3,startDate:'2026-09-01',finePercent:2,interestPercentMonthly:3},'USR-1');}

test('painel separa vencido, hoje e próximos 7 dias com dados de cliente e veículo',()=>{const d=buildDelinquency(planned(),{asOf:'2026-09-08T00:00:00Z'});assert.equal(d.rows.length,1);assert.equal(d.rows[0].customerName,'Ana');assert.equal(d.rows[0].vehiclePlate,'ABC1D23');assert.equal(d.rows[0].daysLate,7);assert.equal(d.summary.delinquentCustomers,1);assert.equal(d.summary.dueToday,100);assert.equal(d.summary.dueNext7Days,100);assert.ok(d.summary.overdueTotal>100);});
test('aging agrupa faixas 1-7, 8-15, 16-30, 31-60 e 60+',()=>{let s=planned();const inst=s.billingInstallments;inst[0].dueAt='2026-09-01';inst[1].dueAt='2026-08-25';inst[2].dueAt='2026-07-20';const report=buildAgingReport(s,{asOf:'2026-09-09T00:00:00Z'});assert.equal(report.find(x=>x.bucket==='8–15').count,2);assert.equal(report.find(x=>x.bucket==='31–60').count,1);assert.equal(report.reduce((sum,x)=>sum+x.count,0),3);});
test('régua de cobrança registra canal, promessa e próxima ação com auditoria',()=>{let s=planned();const installment=s.billingInstallments[0];s=addCollectionActivity(s,{customerId:'CLI-1',rentalId:'LOC-1',installmentId:installment.id,channel:'whatsapp',note:'Cliente pediu prazo',promiseDate:'2026-09-15',nextActionAt:'2026-09-12'},'USR-1');assert.equal(s.collectionActivities.length,1);assert.equal(s.collectionActivities[0].promiseDate,'2026-09-15');assert.equal(s.collectionActivities[0].channel,'whatsapp');assert.equal(s.audit[0].action,'collection_activity.created');});