import test from 'node:test';
import assert from 'node:assert/strict';
import { ensureP1Snapshot } from '../src/domain/p1.mjs';
import { moveRental } from '../src/domain/rental.mjs';
import { createInspection, setInspectionItem, addInspectionPhoto, completeInspection, inspectionProgress } from '../src/domain/inspection.mjs';
import { scheduleMaintenance, startMaintenance, completeMaintenance, maintenanceDue, syncMaintenanceAvailability } from '../src/domain/maintenance.mjs';
import { buildOperationalAlerts, acknowledgeAlert, dismissAlert } from '../src/domain/alerts.mjs';
import { buildDashboard } from '../src/domain/reports.mjs';
import { rentalContractPdf, rentalReceiptPdf, inspectionPdf } from '../src/domain/documents.mjs';

function base(){return ensureP1Snapshot({version:2,updatedAt:'2026-09-14T10:00:00Z',customers:[{id:'CLI-1',name:'Ana',document:'1',phone:'1',active:true}],vehicles:[{id:'VEI-1',model:'Onix',plate:'ABC1D23',mileage:10000,availability:'disponivel'}],rentals:[{id:'LOC-1',vehicleId:'VEI-1',customerId:'CLI-1',pickupAt:'2026-09-13T10:00:00Z',returnAt:'2026-09-14T09:00:00Z',status:'em_uso',total:500,paymentStatus:'aberto',payments:[]}],expenses:[],ledger:[{id:'FIN-1',kind:'receivable',rentalId:'LOC-1',vehicleId:'VEI-1',amount:500,paidAmount:200,status:'partial'}],audit:[],settings:{companyName:'Locadora Teste'}});}

test('P1 normaliza snapshot antigo sem perder dados',()=>{const s=base();assert.equal(s.version,4);assert.deepEqual(s.inspections,[]);assert.deepEqual(s.maintenance,[]);assert.equal(s.customers[0].driverLicense.expiry,'');assert.equal(s.vehicles[0].documents.insuranceExpiry,'');});

test('vistoria registra checklist, foto, km e conclusão',()=>{let initial=base();initial.rentals[0].status='reserva';let s=createInspection(initial,{rentalId:'LOC-1',kind:'checkout'},'USR-1');const id=s.inspections[0].id;for(const item of s.inspections[0].checklist){if(!['mileage','fuel','photos'].includes(item.id))s=setInspectionItem(s,id,item.id,{done:true},'USR-1');}s=addInspectionPhoto(s,id,{dataUrl:'data:image/jpeg;base64,AA==',name:'frente.jpg'},'USR-1');s=completeInspection(s,id,{mileage:10123,fuelLevel:'3/4',damages:[]},'USR-1');assert.equal(s.inspections[0].status,'completed');assert.equal(s.vehicles[0].mileage,10123);assert.equal(inspectionProgress(s.inspections[0]).completed>=3,true);assert.equal(s.inspections[0].photos.length,1);});

test('manutenção bloqueia e libera veículo sem locação ativa',()=>{let initial=base();initial.rentals[0].status='devolucao';let s=scheduleMaintenance(initial,{vehicleId:'VEI-1',type:'Troca de óleo',dueMileage:10000},'USR-1');const id=s.maintenance[0].id;assert.equal(maintenanceDue(s.maintenance[0],s.vehicles[0],new Date('2026-09-14T10:00:00Z')),true);s=startMaintenance(s,id,'USR-1');assert.equal(s.vehicles[0].availability,'manutencao');s=completeMaintenance(s,id,{cost:350,mileage:10100},'USR-1');assert.equal(s.vehicles[0].availability,'disponivel');assert.equal(s.maintenance[0].cost,350);assert.equal(s.expenses[0].category,'Manutenção');assert.equal(s.ledger[0].kind,'expense');});

test('manutenção vencida bloqueia automaticamente veículo disponível',()=>{let s=scheduleMaintenance(base(),{vehicleId:'VEI-1',type:'Óleo',dueMileage:9000},'USR-1');s=syncMaintenanceAvailability(s,new Date('2026-09-14T10:00:00Z'));assert.equal(s.vehicles[0].availability,'manutencao');});

test('alertas cobrem atraso, manutenção, documentos e CNH e aceitam reconhecimento',()=>{let s=base();s.vehicles[0].documents.insuranceExpiry='2026-09-20T00:00:00Z';s.customers[0].driverLicense.expiry='2026-09-10T00:00:00Z';s=scheduleMaintenance(s,{vehicleId:'VEI-1',type:'Óleo',dueMileage:9000},'USR-1');let alerts=buildOperationalAlerts(s,new Date('2026-09-14T10:00:00Z'));assert.equal(alerts.some(a=>a.kind==='rental_overdue'),true);assert.equal(alerts.some(a=>a.kind==='maintenance'),true);assert.equal(alerts.some(a=>a.kind==='vehicle_document'),true);assert.equal(alerts.some(a=>a.kind==='driver_license'),true);const id=alerts[0].id;s=acknowledgeAlert(s,id,'USR-1');assert.equal(buildOperationalAlerts(s,new Date('2026-09-14T10:00:00Z')).find(a=>a.id===id).status,'acknowledged');s=dismissAlert(s,id,'USR-1');assert.equal(buildOperationalAlerts(s,new Date('2026-09-14T10:00:00Z')).some(a=>a.id===id),false);});

test('dashboard calcula ocupação, financeiro e rentabilidade por veículo',()=>{const d=buildDashboard(base(),new Date('2026-09-14T10:00:00Z'));assert.equal(d.fleetTotal,1);assert.equal(d.occupancyRate,100);assert.equal(d.grossRevenue,500);assert.equal(d.received,200);assert.equal(d.vehiclePerformance[0].revenue,200);});

test('documentos geram PDFs válidos para contrato, recibo e vistoria',()=>{let initial=base();initial.rentals[0].status='reserva';let s=createInspection(initial,{rentalId:'LOC-1'},'USR-1');const id=s.inspections[0].id;for(const item of s.inspections[0].checklist){if(!['mileage','fuel','photos'].includes(item.id))s=setInspectionItem(s,id,item.id,{done:true},'USR-1');}s=addInspectionPhoto(s,id,{dataUrl:'data:image/jpeg;base64,AA=='},'USR-1');s=completeInspection(s,id,{mileage:10001,fuelLevel:'Cheio'},'USR-1');for(const bytes of [rentalContractPdf(s,'LOC-1'),rentalReceiptPdf(s,'LOC-1'),inspectionPdf(s,s.inspections[0].id)]){const text=new TextDecoder().decode(bytes.slice(0,8));assert.equal(text.startsWith('%PDF-1.'),true);assert.equal(bytes.length>300,true);}});


test('P1 bloqueia devolução sem vistoria de retirada concluída',()=>{assert.throws(()=>createInspection(base(),{rentalId:'LOC-1',kind:'return'},'USR-1'),/retirada/i);});

test('P1 manutenção concluída não libera veículo com locação ativa',()=>{let s=base();s.vehicles[0].availability='locado';s=scheduleMaintenance(s,{vehicleId:'VEI-1',type:'Emergencial',dueMileage:10000},'USR-1');const id=s.maintenance[0].id;s=startMaintenance(s,id,'USR-1');s=completeMaintenance(s,id,{cost:10,mileage:10100},'USR-1');assert.equal(s.vehicles[0].availability,'locado');});


test('P1 locação exige vistorias concluídas para entrar em uso e devolver',()=>{let s=base();s.rentals[0].status='retirada';assert.throws(()=>moveRental(s,'LOC-1','em_uso','USR-1'),/vistoria de retirada/i);s.inspections=[{id:'VIS-C',rentalId:'LOC-1',vehicleId:'VEI-1',kind:'checkout',status:'completed',checklist:[],photos:[],completedAt:'2026-09-14T10:00:00Z'}];s=moveRental(s,'LOC-1','em_uso','USR-1');assert.equal(s.rentals[0].status,'em_uso');assert.throws(()=>moveRental(s,'LOC-1','devolucao','USR-1'),/vistoria de devolução/i);s.inspections.unshift({id:'VIS-R',rentalId:'LOC-1',vehicleId:'VEI-1',kind:'return',status:'completed',checklist:[],photos:[],completedAt:'2026-09-14T11:00:00Z'});s=moveRental(s,'LOC-1','devolucao','USR-1');assert.equal(s.rentals[0].status,'devolucao');assert.equal(s.vehicles[0].availability,'disponivel');});
