import { can } from '../domain/auth.mjs';
import { addCustomer, addVehicle } from '../domain/rental.mjs';
import { updateCustomerLicense, updateVehicleDocuments } from '../domain/p1.mjs';
import { closeModal, esc, modal, money, toast } from './common.mjs';

export function renderClientes(view,ctx){
  const {snapshot,sessionUser,save}=ctx;
  view.innerHTML=`<div class="heading"><div><small>CADASTRO</small><h1>Clientes</h1></div>${can(sessionUser,'customer.write')?'<button id="new-customer" class="primary">Novo cliente</button>':''}</div><section class="panel"><div class="table-wrap"><table><thead><tr><th>Nome</th><th>Documento</th><th>Telefone</th><th>CNH</th><th>Validade</th><th>Ações</th></tr></thead><tbody>${snapshot.customers.map(c=>`<tr><td>${esc(c.name)}</td><td>${esc(c.document)}</td><td>${esc(c.phone)}</td><td>${esc(c.driverLicense?.number||'-')}</td><td>${esc(c.driverLicense?.expiry||'-')}</td><td>${can(sessionUser,'customer.write')?`<button data-license="${esc(c.id)}">CNH</button>`:'-'}</td></tr>`).join('')||'<tr><td colspan="6" class="empty">Nenhum cliente.</td></tr>'}</tbody></table></div></section>`;
  view.querySelector('#new-customer')?.addEventListener('click',()=>modal('Novo cliente',`<form id="customer-form" class="form-grid"><label>Nome<input name="name" required></label><label>CPF/CNPJ<input name="document" required></label><label>Telefone<input name="phone" required></label><label>E-mail<input name="email" type="email"></label><label class="full">Endereço<input name="address"></label><div class="full modal-actions"><button type="button" data-close>Cancelar</button><button class="primary">Salvar</button></div></form>`,()=>{const f=document.querySelector('#customer-form');f.onsubmit=e=>{e.preventDefault();try{save(addCustomer(snapshot,Object.fromEntries(new FormData(f)),sessionUser.id));closeModal();toast('Cliente cadastrado.');}catch(err){toast(err.message)}};}));
  view.querySelectorAll('[data-license]').forEach(b=>b.onclick=()=>{const c=snapshot.customers.find(x=>x.id===b.dataset.license);modal(`CNH · ${c.name}`,`<form id="license-form" class="form-grid"><label>Número<input name="number" value="${esc(c.driverLicense?.number||'')}"></label><label>Categoria<input name="category" value="${esc(c.driverLicense?.category||'')}"></label><label>Validade<input name="expiry" type="date" value="${esc((c.driverLicense?.expiry||'').slice(0,10))}"></label><div class="full modal-actions"><button type="button" data-close>Cancelar</button><button class="primary">Salvar</button></div></form>`,()=>{const f=document.querySelector('#license-form');f.onsubmit=e=>{e.preventDefault();save(updateCustomerLicense(snapshot,c.id,Object.fromEntries(new FormData(f)),sessionUser.id));closeModal();toast('CNH atualizada.');};});});
}

export function renderFrota(view,ctx){
  const {snapshot,sessionUser,save}=ctx;
  view.innerHTML=`<div class="heading"><div><small>CONTROLE DE FROTA</small><h1>Frota</h1></div><button id="new-vehicle" class="primary">Novo veículo</button></div><div class="vehicle-grid">${snapshot.vehicles.map(v=>`<article class="vehicle"><div><small>${esc(v.category)}</small><h3>${esc(v.model)}</h3><b>${esc(v.plate)}</b></div><dl><div><dt>Ano</dt><dd>${esc(v.year)}</dd></div><div><dt>KM</dt><dd>${Number(v.mileage).toLocaleString('pt-BR')}</dd></div><div><dt>Diária</dt><dd>${money(v.dailyRate)}</dd></div><div><dt>Status</dt><dd>${esc(v.availability)}</dd></div></dl><div class="vehicle-actions"><button data-docs="${esc(v.id)}">Documentos</button></div></article>`).join('')||'<div class="empty">Nenhum veículo cadastrado.</div>'}</div>`;
  view.querySelector('#new-vehicle').onclick=()=>modal('Novo veículo',`<form id="vehicle-form" class="form-grid"><label>Modelo<input name="model" required></label><label>Placa<input name="plate" required></label><label>Ano<input name="year" required></label><label>Categoria<input name="category"></label><label>Cor<input name="color"></label><label>KM<input name="mileage" type="number" min="0"></label><label>Valor da diária<input name="dailyRate" type="number" step="0.01" required></label><label>Valor de compra<input name="purchasePrice" type="number" step="0.01"></label><div class="full modal-actions"><button type="button" data-close>Cancelar</button><button class="primary">Salvar</button></div></form>`,()=>{const f=document.querySelector('#vehicle-form');f.onsubmit=e=>{e.preventDefault();save(addVehicle(snapshot,Object.fromEntries(new FormData(f)),sessionUser.id));closeModal();toast('Veículo cadastrado.');};});
  view.querySelectorAll('[data-docs]').forEach(b=>b.onclick=()=>{const v=snapshot.vehicles.find(x=>x.id===b.dataset.docs);modal(`Documentos · ${v.model}`,`<form id="vehicle-docs-form" class="form-grid"><label>Seguro até<input name="insuranceExpiry" type="date" value="${esc((v.documents?.insuranceExpiry||'').slice(0,10))}"></label><label>Licenciamento até<input name="licensingExpiry" type="date" value="${esc((v.documents?.licensingExpiry||'').slice(0,10))}"></label><label>Inspeção até<input name="inspectionExpiry" type="date" value="${esc((v.documents?.inspectionExpiry||'').slice(0,10))}"></label><div class="full modal-actions"><button type="button" data-close>Cancelar</button><button class="primary">Salvar</button></div></form>`,()=>{const f=document.querySelector('#vehicle-docs-form');f.onsubmit=e=>{e.preventDefault();save(updateVehicleDocuments(snapshot,v.id,Object.fromEntries(new FormData(f)),sessionUser.id));closeModal();toast('Documentos atualizados.');};});});
}
