import { can } from '../domain/auth.mjs';
import {
  createContractTemplate, updateContractTemplate, duplicateContractTemplate, deactivateContractTemplate,
  contractTemplatePreview, issueContract, createBillingPlan, installmentBalance, recordInstallmentPayment,
  delinquencySummary, recordCollectionAction, customerDelinquencyReport
} from '../domain/commercial.mjs';
import { issuedContractPdf } from '../domain/documents.mjs';
import { closeModal, esc, modal, money, toast } from './common.mjs';

function pdf(name,bytes){const blob=new Blob([bytes],{type:'application/pdf'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url);}
function shortDate(value){if(!value)return'-';const d=new Date(`${String(value).slice(0,10)}T12:00:00`);return Number.isFinite(d.getTime())?d.toLocaleDateString('pt-BR'):String(value);}
function rentalLabel(snapshot,rental){const customer=snapshot.customers.find(x=>x.id===rental.customerId),vehicle=snapshot.vehicles.find(x=>x.id===rental.vehicleId);return `${rental.id} · ${customer?.name??'-'} · ${vehicle?.model??'-'} ${vehicle?.plate??''}`;}

export function renderContracts(view,ctx){
  const {snapshot,sessionUser}=ctx,writable=can(sessionUser,'contracts.write');
  if(!can(sessionUser,'contracts.read')){view.innerHTML='<div class="empty">Sem permissão.</div>';return;}
  view.innerHTML=`<div class="heading"><div><small>CONTRATOS</small><h1>Modelos e emissões</h1></div>${writable?'<button id="new-template" class="primary">Novo modelo</button>':''}</div>
  <section class="panel"><h2>Modelos</h2><div class="table-wrap"><table><thead><tr><th>Nome</th><th>Versão</th><th>Status</th><th>Padrão</th><th>Ações</th></tr></thead><tbody>${snapshot.contractTemplates.map(t=>`<tr><td>${esc(t.name)}</td><td>v${t.version}</td><td>${t.active?'Ativo':'Inativo'}</td><td>${t.isDefault?'Sim':'-'}</td><td>${t.active?`<button data-preview-template="${esc(t.id)}">Prévia</button> `:''}${writable?`<button data-edit-template="${esc(t.id)}">Editar</button> <button data-duplicate-template="${esc(t.id)}">Duplicar</button> ${t.active?`<button data-disable-template="${esc(t.id)}">Desativar</button>`:''}`:'-'}</td></tr>`).join('')||'<tr><td colspan="5" class="empty">Nenhum modelo cadastrado.</td></tr>'}</tbody></table></div></section>
  <section class="panel"><div class="panel-head"><h2>Contratos emitidos</h2>${writable&&snapshot.contractTemplates.some(t=>t.active)?'<button id="issue-contract">Emitir contrato</button>':''}</div><div class="table-wrap"><table><thead><tr><th>ID</th><th>Locação</th><th>Modelo</th><th>Versão</th><th>Emissão</th><th>PDF</th></tr></thead><tbody>${snapshot.issuedContracts.map(i=>`<tr><td>${esc(i.id)}</td><td>${esc(i.rentalId)}</td><td>${esc(i.templateName)}</td><td>v${i.templateVersion}</td><td>${new Date(i.createdAt).toLocaleString('pt-BR')}</td><td><button data-issued-pdf="${esc(i.id)}">PDF</button></td></tr>`).join('')||'<tr><td colspan="6" class="empty">Nenhum contrato emitido.</td></tr>'}</tbody></table></div></section>`;
  view.querySelector('#new-template')?.addEventListener('click',()=>showTemplate(ctx));
  view.querySelectorAll('[data-preview-template]').forEach(b=>b.onclick=()=>showContractPreview(ctx,b.dataset.previewTemplate));
  view.querySelectorAll('[data-edit-template]').forEach(b=>b.onclick=()=>showTemplate(ctx,b.dataset.editTemplate));
  view.querySelectorAll('[data-duplicate-template]').forEach(b=>b.onclick=()=>{try{ctx.save(duplicateContractTemplate(snapshot,b.dataset.duplicateTemplate,sessionUser.id));toast('Modelo duplicado.');}catch(e){toast(e.message)}});
  view.querySelectorAll('[data-disable-template]').forEach(b=>b.onclick=()=>{try{ctx.save(deactivateContractTemplate(snapshot,b.dataset.disableTemplate,sessionUser.id));toast('Modelo desativado.');}catch(e){toast(e.message)}});
  view.querySelector('#issue-contract')?.addEventListener('click',()=>showIssue(ctx));
  view.querySelectorAll('[data-issued-pdf]').forEach(b=>b.onclick=()=>pdf(`contrato-${b.dataset.issuedPdf}.pdf`,issuedContractPdf(snapshot,b.dataset.issuedPdf)));
}

function showTemplate(ctx,id=null){
  const {snapshot,sessionUser,save}=ctx,current=id?snapshot.contractTemplates.find(t=>t.id===id):null;
  const defaultBody='CONTRATO DE LOCAÇÃO\n\nLOCADORA: {{locadora.nome}} - {{locadora.documento}}\nLOCATÁRIO: {{cliente.nome}} - {{cliente.documento}}\nVEÍCULO: {{veiculo.modelo}} - placa {{veiculo.placa}}\nRETIRADA: {{locacao.retirada}}\nDEVOLUÇÃO: {{locacao.devolucao}}\nVALOR TOTAL: {{locacao.valor_total}}\n\nObservações: {{locacao.observacoes}}';
  modal(current?'Editar modelo':'Novo modelo',`<form id="contract-template-form" class="form-grid"><label>Nome<input name="name" value="${esc(current?.name||'')}" required></label><label class="check"><input name="isDefault" type="checkbox" ${current?.isDefault?'checked':''}> Modelo padrão</label><label class="full">Conteúdo<textarea name="body" rows="16" required>${esc(current?.body||defaultBody)}</textarea></label><p class="full hint">Variáveis: {{cliente.nome}}, {{cliente.documento}}, {{cliente.cnh}}, {{veiculo.modelo}}, {{veiculo.placa}}, {{veiculo.km}}, {{locacao.valor_total}}, {{locacao.retirada}}, {{locacao.devolucao}}, {{locadora.nome}}, {{atendente.nome}}.</p><div class="full modal-actions"><button type="button" data-close>Cancelar</button><button class="primary">Salvar</button></div></form>`,()=>{const form=document.querySelector('#contract-template-form');form.onsubmit=e=>{e.preventDefault();const fd=Object.fromEntries(new FormData(form)),draft={name:fd.name,body:fd.body,isDefault:form.elements.isDefault.checked};try{save(current?updateContractTemplate(snapshot,current.id,draft,sessionUser.id):createContractTemplate(snapshot,draft,sessionUser.id));closeModal();toast('Modelo salvo.');}catch(err){toast(err.message)}};});
}

function showContractPreview(ctx,templateId){
  const {snapshot}=ctx;if(!snapshot.rentals.length){toast('Cadastre uma locação para visualizar o modelo com dados reais.');return;}
  modal('Prévia do contrato',`<div class="form-grid"><label class="full">Usar dados da locação<select id="preview-rental">${snapshot.rentals.map(r=>`<option value="${esc(r.id)}">${esc(rentalLabel(snapshot,r))}</option>`).join('')}</select></label><div id="contract-preview" class="full panel"></div><div class="full modal-actions"><button type="button" data-close>Fechar</button></div></div>`,()=>{const select=document.querySelector('#preview-rental'),target=document.querySelector('#contract-preview');const renderPreview=()=>{try{const result=contractTemplatePreview(snapshot,templateId,select.value);target.innerHTML=`${result.unknownVariables.length?`<p class="error"><b>Variáveis desconhecidas:</b> ${esc(result.unknownVariables.join(', '))}</p>`:''}<pre style="white-space:pre-wrap">${esc(result.renderedText)}</pre>`;}catch(error){target.innerHTML=`<p class="error">${esc(error.message)}</p>`;}};select.onchange=renderPreview;renderPreview();});
}

function showIssue(ctx){
  const {snapshot,sessionUser,save}=ctx;
  modal('Emitir contrato',`<form id="issue-contract-form" class="form-grid"><label class="full">Locação<select name="rentalId" required>${snapshot.rentals.map(r=>`<option value="${esc(r.id)}">${esc(rentalLabel(snapshot,r))}</option>`).join('')}</select></label><label class="full">Modelo<select name="templateId" required>${snapshot.contractTemplates.filter(t=>t.active).map(t=>`<option value="${esc(t.id)}" ${t.isDefault?'selected':''}>${esc(t.name)} · v${t.version}</option>`).join('')}</select></label><div class="full modal-actions"><button type="button" data-close>Cancelar</button><button class="primary">Emitir</button></div></form>`,()=>{const form=document.querySelector('#issue-contract-form');form.onsubmit=e=>{e.preventDefault();const fd=Object.fromEntries(new FormData(form));try{const next=issueContract(snapshot,fd,sessionUser.id);save(next);closeModal();const issued=next.issuedContracts[0];pdf(`contrato-${issued.id}.pdf`,issuedContractPdf(next,issued.id));toast('Contrato emitido e preservado no histórico.');}catch(err){toast(err.message)}};});
}

export function renderBilling(view,ctx){
  const {snapshot,sessionUser}=ctx,writable=can(sessionUser,'billing.write');
  if(!can(sessionUser,'billing.read')){view.innerHTML='<div class="empty">Sem permissão.</div>';return;}
  const now=new Date().toISOString(),rows=snapshot.billingInstallments.map(i=>({i,b:installmentBalance(i,now)}));
  const open=rows.filter(x=>x.i.status!=='paid'&&x.i.status!=='cancelled').reduce((s,x)=>s+x.b.totalDue,0),overdue=rows.filter(x=>x.b.daysLate>0&&!['paid','cancelled'].includes(x.i.status)).reduce((s,x)=>s+x.b.totalDue,0);
  view.innerHTML=`<div class="heading"><div><small>COBRANÇAS</small><h1>Recorrências e parcelas</h1></div>${writable?'<button id="new-plan" class="primary">Nova recorrência</button>':''}</div><div class="cards"><article><small>Planos ativos</small><strong>${snapshot.billingPlans.filter(p=>p.active).length}</strong></article><article><small>Parcelas abertas</small><strong>${rows.filter(x=>!['paid','cancelled'].includes(x.i.status)).length}</strong></article><article><small>Saldo aberto</small><strong>${money(open)}</strong></article><article><small>Vencido</small><strong>${money(overdue)}</strong></article></div>
  <section class="panel"><h2>Parcelas</h2><div class="table-wrap"><table><thead><tr><th>Vencimento</th><th>Cliente</th><th>Locação</th><th>Principal</th><th>Pago</th><th>Encargos hoje</th><th>Saldo</th><th>Status</th><th></th></tr></thead><tbody>${rows.map(({i,b})=>{const c=snapshot.customers.find(x=>x.id===i.customerId);return`<tr><td>${shortDate(i.dueAt)}</td><td>${esc(c?.name||i.customerId)}</td><td>${esc(i.rentalId)}</td><td>${money(i.amount)}</td><td>${money(i.paidAmount)}</td><td>${money(b.fine+b.interest)}</td><td>${money(b.totalDue)}</td><td>${i.status==='paid'?'Pago':i.status==='cancelled'?'Cancelada':b.daysLate>0?`Vencida ${b.daysLate}d`:i.status==='partial'?'Parcial':'Aberta'}</td><td>${writable&&!['paid','cancelled'].includes(i.status)?`<button data-pay-installment="${esc(i.id)}">Receber</button>`:''}</td></tr>`}).join('')||'<tr><td colspan="9" class="empty">Nenhuma parcela.</td></tr>'}</tbody></table></div></section>`;
  view.querySelector('#new-plan')?.addEventListener('click',()=>showBillingPlan(ctx));
  view.querySelectorAll('[data-pay-installment]').forEach(b=>b.onclick=()=>showInstallmentPayment(ctx,b.dataset.payInstallment));
}

function showBillingPlan(ctx){
  const {snapshot,sessionUser,save}=ctx;
  modal('Nova cobrança recorrente',`<form id="billing-plan-form" class="form-grid"><label class="full">Locação<select name="rentalId" required>${snapshot.rentals.map(r=>`<option value="${esc(r.id)}">${esc(rentalLabel(snapshot,r))}</option>`).join('')}</select></label><label>Periodicidade<select name="frequency"><option value="monthly">Mensal</option><option value="biweekly">Quinzenal</option><option value="weekly">Semanal</option><option value="daily">Diária</option><option value="custom">Personalizada</option></select></label><label>Dias (personalizada)<input name="customDays" type="number" min="1" value="30"></label><label>Primeiro vencimento<input name="firstDueAt" type="date" required></label><label>Valor por parcela<input name="amount" type="number" min="0.01" step="0.01" required></label><label>Quantidade<input name="occurrences" type="number" min="1" max="120" value="1" required></label><label>Multa %<input name="finePercent" type="number" min="0" step="0.01" value="2"></label><label>Juros % ao mês<input name="interestMonthlyPercent" type="number" min="0" step="0.01" value="1"></label><div class="full modal-actions"><button type="button" data-close>Cancelar</button><button class="primary">Gerar parcelas</button></div></form>`,()=>{const form=document.querySelector('#billing-plan-form');form.onsubmit=e=>{e.preventDefault();const fd=Object.fromEntries(new FormData(form));try{save(createBillingPlan(snapshot,fd,sessionUser.id));closeModal();toast('Recorrência e parcelas criadas.');}catch(err){toast(err.message)}};});
}

function showInstallmentPayment(ctx,id){
  const {snapshot,sessionUser,save}=ctx,item=snapshot.billingInstallments.find(i=>i.id===id),balance=installmentBalance(item,new Date().toISOString());
  modal('Receber parcela',`<form id="installment-payment-form" class="form-grid"><label>Saldo atualizado<input value="${balance.totalDue.toFixed(2)}" disabled></label><label>Valor<input name="amount" type="number" min="0.01" max="${balance.totalDue}" step="0.01" required></label><label>Forma<select name="method"><option>PIX</option><option>Dinheiro</option><option>Crédito</option><option>Débito</option><option>Boleto</option></select></label><div class="full modal-actions"><button type="button" data-close>Cancelar</button><button class="primary">Confirmar</button></div></form>`,()=>{const form=document.querySelector('#installment-payment-form');form.onsubmit=e=>{e.preventDefault();const fd=Object.fromEntries(new FormData(form));try{save(recordInstallmentPayment(snapshot,id,{amount:Number(fd.amount),method:fd.method},sessionUser.id));closeModal();toast('Pagamento registrado.');}catch(err){toast(err.message)}};});
}

export function renderDelinquency(view,ctx){
  const {snapshot,sessionUser}=ctx;
  if(!can(sessionUser,'billing.read')){view.innerHTML='<div class="empty">Sem permissão.</div>';return;}
  const summary=delinquencySummary(snapshot,new Date().toISOString()),report=customerDelinquencyReport(snapshot,new Date().toISOString()),writable=can(sessionUser,'billing.write');
  view.innerHTML=`<div class="heading"><div><small>INADIMPLÊNCIA</small><h1>Vencidos e régua de cobrança</h1></div></div><div class="cards six"><article><small>Total vencido</small><strong>${money(summary.total)}</strong></article><article><small>Clientes</small><strong>${summary.customers}</strong></article><article><small>Vence hoje</small><strong>${money(summary.dueToday)}</strong></article><article><small>Próximos 7 dias</small><strong>${money(summary.dueNext7Days)}</strong></article><article><small>Parcelas vencidas</small><strong>${summary.count}</strong></article><article><small>Atraso médio</small><strong>${summary.averageDaysLate} dias</strong></article></div>
  <section class="panel"><h2>Aging</h2><div class="cards five">${Object.entries(summary.aging).map(([label,value])=>`<article><small>${label} dias</small><strong>${money(value)}</strong></article>`).join('')}</div></section>
  <section class="panel"><h2>Parcelas vencidas</h2><div class="table-wrap"><table><thead><tr><th>Cliente</th><th>Veículo</th><th>Vencimento</th><th>Atraso</th><th>Principal</th><th>Multa</th><th>Juros</th><th>Total</th><th></th></tr></thead><tbody>${summary.rows.map(({item,balance})=>{const c=snapshot.customers.find(x=>x.id===item.customerId),v=snapshot.vehicles.find(x=>x.id===item.vehicleId);return`<tr><td>${esc(c?.name||item.customerId)}</td><td>${esc(v?.model||'-')}<small>${esc(v?.plate||'')}</small></td><td>${shortDate(item.dueAt)}</td><td>${balance.daysLate} dias</td><td>${money(balance.outstanding)}</td><td>${money(balance.fine)}</td><td>${money(balance.interest)}</td><td><b>${money(balance.totalDue)}</b></td><td>${writable?`<button data-collect="${esc(item.id)}">Registrar contato</button>`:''}</td></tr>`}).join('')||'<tr><td colspan="9" class="empty">Nenhuma inadimplência.</td></tr>'}</tbody></table></div></section>
  <div class="split"><section class="panel"><h2>Maiores devedores</h2>${report.map(r=>`<p class="kpi-line"><span>${esc(r.customer)} · ${r.count} parcela(s) · ${r.maxDaysLate}d</span><b>${money(r.total)}</b></p>`).join('')||'<div class="empty">Sem devedores.</div>'}</section><section class="panel"><h2>Histórico de cobrança</h2>${snapshot.collectionActions.slice(0,20).map(a=>{const c=snapshot.customers.find(x=>x.id===a.customerId);return`<p><b>${esc(c?.name||a.customerId)}</b><small>${new Date(a.createdAt).toLocaleString('pt-BR')} · ${esc(a.channel)}</small><br>${esc(a.note||'-')}${a.promiseAt?`<small> Promessa: ${shortDate(a.promiseAt)}</small>`:''}${a.nextActionAt?`<small> Próxima ação: ${shortDate(a.nextActionAt)}</small>`:''}</p>`}).join('')||'<div class="empty">Nenhum contato registrado.</div>'}</section></div>`;
  view.querySelectorAll('[data-collect]').forEach(b=>b.onclick=()=>showCollection(ctx,b.dataset.collect));
}

function showCollection(ctx,installmentId){
  const {snapshot,sessionUser,save}=ctx;
  modal('Registrar cobrança',`<form id="collection-form" class="form-grid"><label>Canal<select name="channel"><option>WhatsApp</option><option>Telefone</option><option>E-mail</option><option>Presencial</option><option>Outro</option></select></label><label>Promessa de pagamento<input name="promiseAt" type="date"></label><label>Próxima ação<input name="nextActionAt" type="date"></label><label class="full">Observação<textarea name="note" required></textarea></label><div class="full modal-actions"><button type="button" data-close>Cancelar</button><button class="primary">Registrar</button></div></form>`,()=>{const form=document.querySelector('#collection-form');form.onsubmit=e=>{e.preventDefault();const fd=Object.fromEntries(new FormData(form));try{save(recordCollectionAction(snapshot,{installmentId,...fd},sessionUser.id));closeModal();toast('Contato de cobrança registrado.');}catch(err){toast(err.message)}};});
}
